services:
  # Main Node.js API Service
  - type: web
    name: portfolio-api
    env: node
    plan: starter
    buildCommand: NODE_OPTIONS="--max-old-space-size=2048" npm ci && npm run build:render
    startCommand: NODE_OPTIONS="--max-old-space-size=400" npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Redis connection using connection string (more reliable)
      - key: REDIS_URL
        fromService:
          type: redis
          name: portfolio-redis
          property: connectionString
      # Individual Redis components as backup
      - key: REDIS_HOST
        fromService:
          type: redis
          name: portfolio-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: portfolio-redis
          property: port
      - key: REDIS_PASSWORD
        value: ''
      # Add your other environment variables here
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: CORS_URL
        value: https://your-frontend-domain.com
  # Redis Cache Service
  - type: redis
    name: portfolio-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
